version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.codeborne:selenide
    versions:
    - 5.18.0
    - 5.18.1
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.20.3
  - dependency-name: com.mycila:license-maven-plugin
    versions:
    - "4.0"
  - dependency-name: com.mycila:license-maven-plugin-git
    versions:
    - "4.0"
  - dependency-name: org.owasp:dependency-check-maven
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.1.3
    - 6.1.4
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
